---
- name: Deploy App to Local Docker
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Build Docker Image
      command: /usr/bin/docker build -t myapp .
      args:
        chdir: ../

    - name: Run Docker Container
      command: /usr/bin/docker run -d -p 4000:80 myapp
